# Site settings
title: Thomas Werner
description: 'Business Card Page'
url: 'https://www.thomas-werner.engineer'
baseurl: ''
profilepic: '/images/twerner.jpg'
bkimage: '/images/scott-webb-OxHPDs4WV8Y-unsplash.jpg'
font_awesome: '53d7a3a62b.js'

author:
  name: 'Thomas Werner'
  email: mail@thomas-werner.engineer
  github_username:  huddeldaddel
  linkedin_username:  t-werner  

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  input: GFM
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
